"""Create tables

Revision ID: 80504bcf8783
Revises: c3a9219e2d68
Create Date: 2023-06-27 11:45:37.477233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80504bcf8783'
down_revision = 'c3a9219e2d68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
