"""Create tables

Revision ID: 9f8805aef212
Revises: 80504bcf8783
Create Date: 2023-06-27 11:46:07.499647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8805aef212'
down_revision = '80504bcf8783'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
